/** Site-wide labels in हिन्दी and English (exam-screen labels live in i18n.js) */
export const UI = {
  hi: {
    brandSub: 'ऑनलाइन टेस्ट पोर्टल',
    nav: { tests: 'टेस्ट', myTests: 'मेरे टेस्ट', admin: 'एडमिन', help: 'मदद / गाइड', logout: 'लॉग आउट' },
    langLabel: 'भाषा चुनें',
    loading: 'लोड हो रहा है…',
    tryAgain: 'फिर से कोशिश करें',

    auth: {
      loginTitle: 'लॉगिन करें',
      loginSub: 'अपना यूज़रनेम, ईमेल या मोबाइल नंबर और पासवर्ड डालें।',
      identifier: 'यूज़रनेम / ईमेल / मोबाइल नंबर',
      identifierPh: 'जैसे: ravi_k या 9876543210',
      password: 'पासवर्ड',
      passwordPh: 'अपना पासवर्ड लिखें',
      showPassword: 'पासवर्ड दिखाएँ',
      loginBtn: 'लॉगिन करें',
      loggingIn: 'लॉगिन हो रहा है…',
      newHere: 'पहली बार आए हैं?',
      createAccount: 'नया अकाउंट बनाएँ (रजिस्टर)',
      fillBoth: 'कृपया दोनों खाने भरें।',

      registerTitle: 'नया अकाउंट बनाएँ',
      registerSub: 'सभी खाने भरना ज़रूरी है (*)। इसमें सिर्फ़ 1 मिनट लगेगा।',
      name: 'पूरा नाम', namePh: 'जैसे: रवि कुमार',
      email: 'ईमेल', emailPh: 'जैसे: ravi@gmail.com',
      mobile: 'मोबाइल नंबर', mobilePh: '10 अंकों का नंबर, जैसे: 9876543210',
      username: 'यूज़रनेम', usernamePh: 'जैसे: ravi_k (बिना स्पेस के)',
      usernameHint: 'अंग्रेज़ी अक्षर, अंक, _ या . — लीडरबोर्ड पर यही दिखेगा',
      pass: 'पासवर्ड', passPh: 'कम से कम 6 अक्षर',
      confirm: 'पासवर्ड दोबारा लिखें', confirmPh: 'वही पासवर्ड फिर से',
      testLang: 'टेस्ट किस भाषा में देना चाहेंगे?',
      testLangHint: 'बाद में भी बदल सकते हैं। प्रश्न हिंदी और अंग्रेज़ी दोनों में रहते हैं।',
      registerBtn: 'रजिस्टर करें',
      registering: 'अकाउंट बन रहा है…',
      already: 'पहले से अकाउंट है?',
      goLogin: 'लॉगिन करें',
      mandatory: 'ज़रूरी',
    },

    err: {
      nameRequired: 'पूरा नाम लिखना ज़रूरी है',
      nameShort: 'नाम कम से कम 2 अक्षर का होना चाहिए',
      nameChars: 'नाम में केवल अक्षर, स्पेस, . \' और - लिखें',
      emailRequired: 'ईमेल लिखना ज़रूरी है',
      emailInvalid: 'सही ईमेल लिखें, जैसे: ravi@gmail.com',
      mobileRequired: 'मोबाइल नंबर लिखना ज़रूरी है',
      mobileInvalid: 'सही 10 अंकों का मोबाइल नंबर लिखें (6, 7, 8 या 9 से शुरू)',
      usernameRequired: 'यूज़रनेम लिखना ज़रूरी है',
      usernameInvalid: 'यूज़रनेम 3 से 30 अक्षर का हो — केवल अंग्रेज़ी अक्षर, अंक, _ या .',
      passwordShort: 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
      confirmRequired: 'पासवर्ड दोबारा लिखें',
      mismatch: 'दोनों पासवर्ड एक जैसे नहीं हैं',
    },

    guide: {
      title: 'वेबसाइट कैसे इस्तेमाल करें?',
      register: ['"नया अकाउंट बनाएँ" दबाएँ।', 'अपना नाम, ईमेल और 10 अंकों का मोबाइल नंबर लिखें।', 'एक यूज़रनेम और पासवर्ड बनाएँ (पासवर्ड याद रखें)।', 'भाषा चुनें — हिंदी या English — और "रजिस्टर करें" दबाएँ।'],
      login: ['यूज़रनेम, ईमेल या मोबाइल नंबर लिखें।', 'अपना पासवर्ड लिखें।', '"लॉगिन करें" दबाएँ।', 'टेस्ट चुनें, निर्देश पढ़ें और टेस्ट शुरू करें।'],
      more: 'पूरी गाइड पढ़ें (फ़ोटो सहित)',
      mentor: 'मार्गदर्शक',
    },

    dash: {
      hello: 'नमस्ते',
      intro: 'कोई भी टेस्ट चुनें और असली परीक्षा जैसे माहौल में दें — टाइमर, प्रश्न पैलेट और हर प्रश्न की व्याख्या के साथ।',
      newHere: 'पहली बार टेस्ट दे रहे हैं?',
      newHereLink: 'यहाँ 2 मिनट में समझें कि टेस्ट कैसे देना है →',
      taken: 'दिए गए टेस्ट', average: 'औसत', best: 'सबसे अच्छा',
      unfinished: 'आपका एक टेस्ट अधूरा है:',
      timerRuns: 'समय चल रहा है।',
      resume: 'टेस्ट जारी रखें',
      searchPh: 'टेस्ट खोजें — जैसे: Teaching, Culture, History',
      tabs: { '': 'सभी', MOCK: 'मॉक टेस्ट', PYQ: 'पिछले वर्ष पैटर्न', PRACTICE: 'अभ्यास' },
      allExams: 'सभी परीक्षाएँ', allSubjects: 'सभी विषय', anyDiff: 'कोई भी स्तर', anyLang: 'कोई भी भाषा',
      finding: 'टेस्ट खोजे जा रहे हैं…',
      noTests: 'कोई टेस्ट नहीं मिला', noTestsHint: 'कोई दूसरा शब्द लिखें या फ़िल्टर हटाएँ।',
      recent: 'हाल के टेस्ट', seeAll: 'सभी देखें',
      th: { test: 'टेस्ट', score: 'अंक', rank: 'रैंक', date: 'तारीख' },
      result: 'परिणाम',
      questions: 'प्रश्न', minutes: 'मिनट', marks: 'कुल अंक', negative: 'माइनस मार्किंग', none: 'नहीं',
      start: 'टेस्ट शुरू करें', leaderboard: 'लीडरबोर्ड',
    },
    cat: { MOCK: 'मॉक टेस्ट', PYQ: 'पिछले वर्ष पैटर्न', PRACTICE: 'अभ्यास' },
    diff: { EASY: 'आसान', MEDIUM: 'मध्यम', HARD: 'कठिन' },
    tlang: { BILINGUAL: 'हिंदी + English', EN: 'English', HI: 'हिंदी' },

    result: {
      calculating: 'परिणाम तैयार हो रहा है…',
      running: 'यह टेस्ट अभी चल रहा है।',
      back: '← मेरे टेस्ट',
      auto: 'समय समाप्त हो गया, इसलिए आपके सेव उत्तरों के साथ टेस्ट अपने-आप सबमिट हो गया।',
      submitted: 'सबमिट किया',
      rank: 'रैंक', of: 'में से',
      correct: 'सही', wrong: 'गलत', skipped: 'छोड़े गए', accuracy: 'सटीकता', percentage: 'प्रतिशत', time: 'लगा समय',
      marks: 'अंक', accNote: 'दिए गए उत्तरों में से सही', pctNote: 'कुल अंकों का',
      review: 'उत्तर और व्याख्या देखें', leaderboard: 'लीडरबोर्ड', again: 'फिर से टेस्ट दें',
    },
    my: {
      title: 'मेरे टेस्ट', none: 'आपने अभी तक कोई टेस्ट नहीं दिया है', browse: 'टेस्ट देखें',
      th: { test: 'टेस्ट', date: 'तारीख', score: 'अंक', time: 'समय', rank: 'रैंक' },
      result: 'परिणाम', review: 'व्याख्या', inProgress: 'चल रहा है', resume: 'जारी रखें',
    },
    lb: {
      back: '← टेस्ट विवरण', title: 'लीडरबोर्ड', participants: 'प्रतिभागी', bestAttempt: 'हर विद्यार्थी का सबसे अच्छा प्रयास',
      yourRank: 'आपकी रैंक', in: 'समय', none: 'अभी तक किसी ने यह टेस्ट सबमिट नहीं किया', beFirst: 'सबसे पहले आप दीजिए!',
      th: { rank: 'रैंक', student: 'विद्यार्थी', score: 'अंक', time: 'समय', submitted: 'सबमिट' },
      you: 'आप', ties: 'बराबर अंक होने पर कम समय वाला ऊपर, फिर पहले सबमिट करने वाला।',
    },
  },

  en: {
    brandSub: 'Online Test Portal',
    nav: { tests: 'Tests', myTests: 'My tests', admin: 'Admin', help: 'Help / Guide', logout: 'Log out' },
    langLabel: 'Choose language',
    loading: 'Loading…',
    tryAgain: 'Try again',

    auth: {
      loginTitle: 'Log in',
      loginSub: 'Enter your username, email or mobile number and your password.',
      identifier: 'Username / Email / Mobile number',
      identifierPh: 'e.g. ravi_k or 9876543210',
      password: 'Password',
      passwordPh: 'Type your password',
      showPassword: 'Show password',
      loginBtn: 'Log in',
      loggingIn: 'Logging in…',
      newHere: 'New here?',
      createAccount: 'Create a new account (Register)',
      fillBoth: 'Please fill in both boxes.',

      registerTitle: 'Create a new account',
      registerSub: 'All fields marked * are required. It takes only a minute.',
      name: 'Full name', namePh: 'e.g. Ravi Kumar',
      email: 'Email', emailPh: 'e.g. ravi@gmail.com',
      mobile: 'Mobile number', mobilePh: '10-digit number, e.g. 9876543210',
      username: 'Username', usernamePh: 'e.g. ravi_k (no spaces)',
      usernameHint: 'Letters, numbers, _ or . — shown on leaderboards',
      pass: 'Password', passPh: 'At least 6 characters',
      confirm: 'Confirm password', confirmPh: 'Type the same password again',
      testLang: 'Which language do you want for tests?',
      testLangHint: 'You can change it later. Every question is available in Hindi and English.',
      registerBtn: 'Register',
      registering: 'Creating account…',
      already: 'Already have an account?',
      goLogin: 'Log in',
      mandatory: 'required',
    },

    err: {
      nameRequired: 'Full name is required',
      nameShort: 'Name must be at least 2 characters',
      nameChars: "Use only letters, spaces, . ' and -",
      emailRequired: 'Email is required',
      emailInvalid: 'Enter a valid email, e.g. ravi@gmail.com',
      mobileRequired: 'Mobile number is required',
      mobileInvalid: 'Enter a valid 10-digit mobile number (starting with 6, 7, 8 or 9)',
      usernameRequired: 'Username is required',
      usernameInvalid: 'Username must be 3–30 characters: letters, numbers, _ or .',
      passwordShort: 'Password must be at least 6 characters',
      confirmRequired: 'Please type the password again',
      mismatch: 'The two passwords do not match',
    },

    guide: {
      title: 'How to use this website',
      register: ['Tap "Create a new account".', 'Write your name, email and 10-digit mobile number.', 'Make a username and a password (remember the password).', 'Choose Hindi or English and tap "Register".'],
      login: ['Type your username, email or mobile number.', 'Type your password.', 'Tap "Log in".', 'Pick a test, read the instructions and start.'],
      more: 'Read the full guide (with pictures)',
      mentor: 'Mentor',
    },

    dash: {
      hello: 'Namaste',
      intro: 'Pick any test and attempt it like the real exam — with timer, question palette and an explanation for every question.',
      newHere: 'Taking a test for the first time?',
      newHereLink: 'Learn how it works in 2 minutes →',
      taken: 'Tests taken', average: 'Average', best: 'Best',
      unfinished: 'You have an unfinished test:',
      timerRuns: 'The timer keeps running.',
      resume: 'Resume test',
      searchPh: 'Search tests — e.g. Teaching, Culture, History',
      tabs: { '': 'All', MOCK: 'Mock tests', PYQ: 'PYQ pattern', PRACTICE: 'Practice' },
      allExams: 'All exams', allSubjects: 'All subjects', anyDiff: 'Any difficulty', anyLang: 'Any language',
      finding: 'Finding tests…',
      noTests: 'No tests match your search', noTestsHint: 'Try a different word or clear the filters.',
      recent: 'Recent attempts', seeAll: 'See all',
      th: { test: 'Test', score: 'Score', rank: 'Rank', date: 'Date' },
      result: 'Result',
      questions: 'Questions', minutes: 'Minutes', marks: 'Marks', negative: 'Negative', none: 'None',
      start: 'Start test', leaderboard: 'Leaderboard',
    },
    cat: { MOCK: 'Mock test', PYQ: 'PYQ pattern', PRACTICE: 'Practice' },
    diff: { EASY: 'Easy', MEDIUM: 'Medium', HARD: 'Hard' },
    tlang: { BILINGUAL: 'Hindi + English', EN: 'English', HI: 'Hindi' },

    result: {
      calculating: 'Calculating result…',
      running: 'This attempt is still running.',
      back: '← My tests',
      auto: 'Time ran out, so the test was submitted automatically with your saved answers.',
      submitted: 'submitted',
      rank: 'Rank', of: 'of',
      correct: 'Correct', wrong: 'Wrong', skipped: 'Unattempted', accuracy: 'Accuracy', percentage: 'Percentage', time: 'Time taken',
      marks: 'marks', accNote: 'correct out of attempted', pctNote: 'of total marks',
      review: 'Review answers & explanations', leaderboard: 'Leaderboard', again: 'Attempt again',
    },
    my: {
      title: 'My tests', none: 'You have not attempted any test yet', browse: 'Browse tests',
      th: { test: 'Test', date: 'Date', score: 'Score', time: 'Time', rank: 'Rank' },
      result: 'Result', review: 'Review', inProgress: 'In progress', resume: 'Resume',
    },
    lb: {
      back: '← Test details', title: 'Leaderboard', participants: 'participant(s)', bestAttempt: 'best attempt per student',
      yourRank: 'Your rank', in: 'in', none: 'No one has submitted this test yet', beFirst: 'Be the first on the board.',
      th: { rank: 'Rank', student: 'Student', score: 'Score', time: 'Time', submitted: 'Submitted' },
      you: 'You', ties: 'Ties are broken by lower time taken, then by earlier submission.',
    },
  },
};

/** Hindi versions of the server's user-facing messages */
const SERVER_HI = {
  'This username is already taken': 'यह यूज़रनेम पहले से लिया जा चुका है, कोई दूसरा चुनें',
  'An account with this email already exists': 'इस ईमेल से पहले से एक अकाउंट बना हुआ है',
  'An account with this mobile number already exists': 'इस मोबाइल नंबर से पहले से एक अकाउंट बना हुआ है',
  'Invalid login details or password': 'यूज़रनेम/ईमेल/मोबाइल या पासवर्ड गलत है',
  'Your account has been blocked. Contact the admin': 'आपका अकाउंट ब्लॉक है। कृपया एडमिन से संपर्क करें',
  'Too many attempts. Please try again in 15 minutes.': 'बहुत बार कोशिश हो गई। 15 मिनट बाद फिर कोशिश करें।',
  'Username / email / mobile and password are required': 'यूज़रनेम/ईमेल/मोबाइल और पासवर्ड लिखना ज़रूरी है',
  'Full name is required': 'पूरा नाम लिखना ज़रूरी है',
  'Email is required': 'ईमेल लिखना ज़रूरी है',
  'Enter a valid email address': 'सही ईमेल लिखें',
  'Mobile number is required': 'मोबाइल नंबर लिखना ज़रूरी है',
  'Enter a valid 10-digit mobile number (starting with 6, 7, 8 or 9)': 'सही 10 अंकों का मोबाइल नंबर लिखें (6, 7, 8 या 9 से शुरू)',
  'Passwords do not match': 'दोनों पासवर्ड एक जैसे नहीं हैं',
  'Password must be at least 6 characters': 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
  'Cannot reach the server. Check your internet connection.': 'सर्वर से संपर्क नहीं हो पाया। इंटरनेट कनेक्शन जाँचें और फिर कोशिश करें।',
};

export function serverMsg(msg, lang) {
  if (lang !== 'hi' || !msg) return msg;
  return SERVER_HI[msg] || msg;
}
